name: BBDM
channels:
  - conda-forge
  - defaults

dependencies:
  # ───────── Core Python / scientific stack ─────────
  - python=3.9.15                # 3.9 series is OK on arm64
  - pip=22.2.2

  - numpy=1.23.5
  - scipy=1.9.1
  - pandas=2.1.1
  - scikit-image=0.20.0
  - scikit-learn=1.5.1
  - matplotlib-base=3.6.2
  - seaborn=0.12.2

  # ───────── BLAS / LAPACK ─────────
  - openblas                     # replaces blas=mkl
  - fftw=3.3.9

  # ───────── Jupyter/IPython stack ─────────
  - ipython=8.8.0
  - ipykernel=6.20.1
  - jupyter_client=7.4.9
  - jupyter_core=5.1.3
  - matplotlib-inline=0.1.6
  - prompt-toolkit=3.0.36
  - pygments=2.14.0

  # ───────── Dask / tooling ─────────
  - dask-core=2023.6.0
  - partd=1.2.0
  - fastparquet               # optional, if you use parquet

  # ───────── Image I/O / codecs ─────────
  - pillow=9.4.0
  - tifffile=2021.7.2
  # (dropped imagecodecs + openjpeg; tifffile can read most common formats)

  # ───────── OpenCV (fallback to pip) ─────────
  # note: removing conda-forge opencv, since its HDF5 chain was unsatisfiable.
  # we'll rely on pip’s “opencv-python” instead:
  - python=3.9  # ensure pip can install a matching wheel

  # ───────── Data structures / utilities ─────────
  - networkx=3.1
  - toolz=0.12.0
  - cytoolz=0.12.0
  - cloudpickle=2.2.1

  # ───────── Compression & file formats ─────────
  - blosc=1.21.3
  - brotli=1.0.9
  - bzip2=1.0.8
  - libpng=1.6.37
  - libjpeg-turbo               # provides JPEG support on arm64
  - libtiff=4.5.0
  - libzopfli=1.0.3
  - snappy=1.1.9
  - zlib=1.2.13
  - zstd=1.5.2

  # ───────── Low-level libs (arm64 builds) ─────────
  - libffi=3.4.2
  - libgcc-ng
  - libstdcxx-ng
  - libxml2=2.9.14
  - libxslt=1.1.35

  # ───────── Video / audio (minimal) ─────────
  - ffmpeg=4.2.3          # 4.2.3 exists on conda-forge/osx-arm64

  # ───────── Misc. utilities ─────────
  - click=8.0.4
  - decorator=5.1.1
  - entrypoints=0.4
  - lazy_loader=0.2
  - packaging=23.1
  - parso=0.8.3
  - pickleshare=0.7.5
  - psutil=5.9.0
  - pyparsing=3.0.9
  - python-dateutil=2.8.2
  - pygments=2.14.0
  - six=1.16.0
  - wcwidth=0.2.5
  - zipp=3.11.0

  # ───────── Jupyter notebook extensions (if needed) ─────────
  - nest-asyncio=1.5.6
  - tornado=6.2
  - traitlets=5.8.1

  # ───────── Remove unsatisfiable / Windows-only / GStreamer-only packages ─────────
  # (cf. original: glib, gstreamer, gst-plugins-base, imagecodecs, cfitsio=3.470,
  #  opencv=4.6.0, openjpeg, hdf5=1.10.6=nompi [nompi builds are tricky], etc.
  #  we’ve dropped all of them.)

  # ───────── Pip-only fallback section ─────────
  - pip:
      - absl-py==2.0.0
      - addict==2.4.0
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - anyio==4.3.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.1.0
      - babel==2.14.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - blobfile==2.1.1
      - cachetools==5.3.2
      - cffi==1.16.0
      - charset-normalizer==2.1.1
      - defusedxml==0.7.1
      - einops==0.8.0
      - et-xmlfile==1.1.0
      - exceptiongroup==1.2.0
      - fastjsonschema==2.19.1
      - filelock==3.9.0
      - fire==0.5.0
      - fqdn==1.5.1
      - frozenlist==1.4.0
      - google-auth==2.23.4
      - google-auth-oauthlib==1.1.0
      - grpcio==1.59.2
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - ibm-db==3.2.3
      - idna==3.4
      - isoduration==20.11.0
      - jinja2==3.1.2
      - joblib==1.4.2
      - json5==0.9.25
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.1.6
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.26.0
      - lightning-utilities==0.3.0
      - lpips==0.1.4
      - lxml==4.9.4
      - markdown==3.5.1
      - markupsafe==2.1.2
      - mistune==3.0.2
      - mpi4py==3.1.5
      - mpmath==1.3.0
      - multidict==6.0.4
      - nbclient==0.10.0
      - nbconvert==7.16.3
      - nbformat==5.10.4
      - ninja==1.11.1.1
      - notebook-shim==0.2.4
      - nystrom-attention==0.0.12
      - oauthlib==3.2.2
      - opencv-python==4.8.1.78   # pip wheel works on arm64
      - openpyxl==3.1.2
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - prometheus-client==0.20.0
      - protobuf==4.23.4
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycparser==2.22
      - pycryptodomex==3.20.0
      - python-json-logger==2.0.7
      - pytorch-fid==0.3.0
      - pytorch-lightning==1.8.1
      - pytorch-toolbelt==0.6.3
      - pytorch-wavelet==1.2
      - pytorch-wavelets==1.3.0
      - pyzmq==26.0.0
      - referencing==0.34.0
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.18.0
      - rsa==4.9
      - send2trash==1.8.3
      - sniffio==1.3.1
      - soupsieve==2.5
      - sympy==1.12
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - termcolor==2.3.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.2.1
      - tomli==2.0.1
      - torch==2.1.0      # CPU build on macOS
      - torchaudio==2.1.0 # CPU build on macOS
      - torchmetrics==0.11.4
      - torchvision==0.16.0 # CPU build on macOS
      - tqdm==4.66.1
      - types-python-dateutil==2.9.0.20240316
      - uri-template==1.3.0
      - urllib3==1.26.13
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - werkzeug==3.0.1
      - yarl==1.9.2

